[package]
name = "coliru"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
expanduser = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
