[package]
name = "coliru"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
shellexpand = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tempfile = "3"
